name: UI

on:
  push:
    branches: 
      - vics-ui-ts

jobs:
# This workflow contains multiple jobs
 CI:
  name: CI deploy
  runs-on: ubuntu-latest

  steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   - name: Checkout Repository
     uses: actions/checkout@v2

   - name: Setup Node.js
     uses: actions/setup-node@v2
     with:
       node-version: 18.8.0

    # install applicaion dependencies
   - name: Install dependencies
     run: npm install
      
    # build the react app
   - name: build
     run: npm run build

   # build the react app
   - name: Unit Testing
     run: npm run coverage
