export const GET_VEHICLECLASSSUBCLASS_URL='/vehicleclasswithsubclass/';
export const GET_VEHICLEMAKES_URL='/vehiclemake/';
export const APPOINTMENT_SEARCH_VEHICLE ='/searchvehicle';
export const GET_VEHICLEPARTICULARSBYID='/vehicleparticularsbyvehicleid/';
export const GET_CENTRES_URI = "/centre/";
export const GET_RECENTAPPOINTMENTS='/recentappointmentforvehicle/';
export const GET_EXAM_CODES= "/getexamcodesforcentre/";
export const GET_LANEALL = "/getlanesbycentreid";
export const GET_EXAM_DATES = "/examSlotavailabilitydetailsfordaterange";
export const GET_EXAM_SLOTS = "/getavailablequotaforselecteddate";
export const CREATEAPPOINTMENT_API = "/createappointment";
export const GET_APPOINTDETAILSBYID = "/getappointmentdetails/";
export const SEARCH_MAINTAIN_EXAM_CODE = "/searchexamcodes";
export const ADD_EXAM_CODE = "/addupdateexamcodes";

export const SEARCHINSPECTIONLANE_API= "/searchlane";
export const ADD_UPDATELANE_API = "/addupdatelane";
export const LOGIN_URL = "/login/UserCredentials";
export const GET_VEHICLECLASS_URL = "/Appointment/GetVehicleClass";
export const APPOINTMENT_SEARCHAPI_URL = "/Appointment/SearchVehicle";
export const APPOINTMENT_SUBCLASS = "/Appointment/Subclass";
export const GET_APPOINTMENT_LETTER ="/Appointment/certificate?appointmentNumber=";
export const BOOKING_STATUS = "/Appointment/BookingStatus";
export const BOOKING_CHANNEL = "/Appointment/BookingChannelList";
export const ENQUIRYAPPOINTMENT_API = "/Appointment/AppointmentEnquiry";
export const GET_APPOINTMENT_DETAIL = "/Appointment/getappointment";
export const DELETE_APPOINTMENT = "/Appointment/deleteappointment?appointmentNumber=";
export const CANCEL_APPOINTMENT = "Appointment/cancelappointment";
export const ENQUIRE_HISTORY_API ="AppointmentEnquiry/getappointmenthistory?appointmentNumber=";
export const AMENDAPPOINTMENTDATA='/Appointment/amendappointment';
export const RESCHEDULEAPPOINTMENT='/Appointment/rescheduleappointment';
export const VEHICLE_ATTACHMENT_SEARCH_API = 'Attachment/searchattachment';
  export const ADDATTACHMENT = 'Attachment/addattachment';
  export const REPRINT_CERTIFICATE = "/Appointment/reprintcertificate?appointmentNumber=";
export const GET_VEHICLEPARTICULAR = "/Appointment/getVehicleInformation?VehicleId=";
export const APPOINTMENTHISTORY_API = '/Attachment/getappointmenthistory?chassisNumber=' ;
export const GET_VEHICLEMAKE_URL = "/Appointment/getvehiclemake";
export const GET_VEHICLESUBCLASS_URL = "/Appointment/subclass";
export const DELETE_ATTACHMENT = "/Attachment/deleteattachment";
export const DOWNLOAD_ATTACHMENTFILE = "Attachment/downloadattachment";
export const GET_SEARCHVEHICLE = "/Appointment/vehicleenquiry";
export const SEARCHVEHICLE_WATCHLIST_API = "/Vehicle/SearchWatchList";
export const OPERATION_REMARK = "/Vehicle/validateOperationRemark";
export const SEARCH_EXAMINATION_SCHEDULE_API = "/Center/searchexamschedule";


