export const LOGIN_URL = "/vicslogin";
export const IP_URL = "/getdetailsbyip";
export const GET_OHM_URL = "/getohm";
export const GET_APPOINTMENT_URL = "/getvehicleinfo";
export const START_INSPECTION_URL = "/startinspection";
export const ADDVEEPAIRING = "/addveepairing";
export const TOGGLECONNECTION_URL = "/toggleconnection";
export const DELETEVEEPAIRING = "/deleteveepairing";
export const ARTUTABLEDETAILS = "/getallentities";
export const SAVE_VISUAL_TEST_RESULT_URL = "/savevisualtestresult";
export const SAVE_EXHAUST_TEST_RESULT_URL = "/saveexhausttestresult";
export const GET_OVERALLRESULT = "/getalltestresults";
export const SAVE_UNDER_CARRIAGE_TEST_RESULT_URL =
  "/saveundercarriagetestresult";
export const SAVE_BRAKE_TEST_RESULT_URL = "/savebraketestresult";
export const SAVE_HT_TEST_RESULT_URL = "/saveheadlamptestresult";
export const SAVE_OHM_TEST_RESULT_URL = "/saveohmtestresult";
export const SAVE_SPEEDOMETER_TEST_RESULT = "/savespeedometertestresult";
export const GET_HEADLAMPCONFIG = "/getheadlampconfig";
export const ARTUTESTRESULTS = "/gettestresult";
export const SAVE_ALL_TEST_RESULT_URL = "/savealltestresult";
export const HEAD_LAMP_TEST_CONFIGURATION_URL = "/headlamptestconfiguration";
export const SAVE_TILTING_TEST_RESULT_URL = "/savetiltingtestresult";
export const GET_ALL_UNCONFIRMED_LIST = "/getallunconfirmedlist";
export const GET_ALL_TESTS_RESULT_URL = "/getalltestresults";
export const ADD_UNCONFIRMED_LIST_URL = "/addunconfirmedlist";
export const GET_ALL_MAINTAIN_EQUIPMENT_DATA="/getAllMaintainEquipmentData"
export const GET_ALL_WORK_STATION_LOCATION ="/getallworkstationlocation"