apiVersion: v1
kind: Service
metadata:
  name: vicss-laneconfiguration-backend-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: vicss-laneconfiguration-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30017
