apiVersion: apps/v1
kind: Deployment
metadata:
  name: vicss-laneconfiguration-backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vicss-laneconfiguration-backend
  template:
    metadata:
      labels:
        app: vicss-laneconfiguration-backend
    spec:
      containers:
        - name: vicss-laneconfiguration-backend
          image: 788148918336.dkr.ecr.ap-east-1.amazonaws.com/dev-microservice-vicss-laneconfiguration:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /app/appsettings.Development.json
            subPath: appsettings.Development.json
      volumes:
        - name: config-volume
          configMap:
            name: backend-configmap  
