apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-scs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-scs
  template:
    metadata:
      labels:
        app: ui-scs
    spec:
      containers:
        - name: ui-scs
          image: 788148918336.dkr.ecr.ap-east-1.amazonaws.com/sit-ui-scs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: ui-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: ui-scs-service-nodeport
spec:
  type: NodePort
  selector:
    app: ui-scs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021
