apiVersion: v1 
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  appsettings.Development.json: |
    {
      "ConnectionStrings": {
        "DefaultConnection": "Server=hktd-devel-sqlserverdb.clk20a8au630.ap-east-1.rds.amazonaws.com;Database=VICSS_SIT;User Id=VICSS_SIT_OWNER;Password=Infosys123;Integrated Security= false; TrustServerCertificate = True; connection timeout= 30;"
      },
      "KafkaConfig": {
        "ProducerServer": "kafka-proto-controller-0.kafka-proto-controller-headless.proto.svc.cluster.local:9092,kafka-proto-controller-1.kafka-proto-controller-headless.proto.svc.cluster.local:9092,kafka-proto-controller-2.kafka-proto-controller-headless.proto.svc.cluster.local:9092",
        "ConsumerServer": "kafka-proto.proto.svc.cluster.local:9092",
        "UserName": "user1",
        "Password": "UaXKBFpI8t"
      },
      "IpDetails": {
        "60.243.75.43": {
          "LaneId": "11",
          "StationId": "A",
          "UserName": "Admin"
        },
        "60.243.75.44": {
          "LaneId": "11",
          "StationId": "B",
          "UserName": "Admin"
        },
        "60.243.75.45": {
          "LaneId": "11",
          "StationId": "C",
          "UserName": "Admin"
        },
        "60.243.75.46": {
          "LaneId": "11",
          "StationId": "D",
          "UserName": "Admin"
        },
        "60.243.75.47": {
          "LaneId": "11",
          "StationId": "E",
          "UserName": "Admin"
        },
        "125.18.110.124": {
          "LaneId": "13",
          "StationId": "A",
          "UserName": "Admin"
        },
        "125.18.110.127": {
          "LaneId": "30",
          "StationId": "A",
          "UserName": "Admin"
        },
        "125.18.110.128": {
          "LaneId": "30",
          "StationId": "B",
          "UserName": "Admin"
        },
        "125.18.110.129": {
          "LaneId": "30",
          "StationId": "C",
          "UserName": "Admin"
        },
        "125.18.110.130": {
          "LaneId": "30",
          "StationId": "D",
          "UserName": "Admin"
        },
        "125.18.110.131": {
          "LaneId": "30",
          "StationId": "E",
          "UserName": "Admin"
        }
      },
      "vehicleInfo": {
        "PassengerSeat": "",
        "UnladenWeight": "",
        "FuelType": "",
        "GVW": "",
        "MaxPAxleWeight": "",
        "VehicleLength": "",
        "VehicleWidth": "",
        "VehicleHeight": "",
        "AWBMeasurementMode": "",
        "BrakeSystem": "",
        "VehicleAxlesNo": "",
        "BRTAxles": "",
        "SecondaryAxles": "",
        "ParkAxles": "",
        "IsTBPark": "",
        "SteeringAxlesType": "",
        "LoadType": "",
        "LoadAxles": "",
        "ParkType": "",
        "IsTricycle": "",
        "TricycleTread": "",
        "WheelBase": "",
        "SpeedOperationMode": "",
        "Steering": "",
        "VehicleHeadlampSystem": "1",
        "MainBeamAdjustable": "",
        "AirIntakeSystem": "",
        "OilSupplyMethod": "",
        "IsThreeWayCC": "",
        "IsDoubleAxlePropulsion": "",
        "CreateTime": "",
        "UpdateTime": "",
        "ExamItem": "",
        "ConnectedState": "",
        "AuxBrkCalType": "",
        "AuxBrkSpType": "",
        "AloneCheckAuxBrk": "",
        "OhmMeasurementMode": "",
        "ParkingType": "",
        "BRTMeasureMethod": "",
        "HeadlampMeasurementMode": "1",
        "InspItem": "F1,C1,B0,B1,B2,BA,S1,H1,H4,X5",
        "SpeedWheelType": "",
        "SetSpeed": "",
        "BeCheckedItems": "",
        "BRTMeasureMode": "",
        "TandemAxle": "",
        "ServiceBrakeCalType": "",
        "SecondaryBrakeCalType": "",
        "ParkingBrakeCalType": "",
        "TmSetMileage": "",
        "StationTimes": "",
        "ParkCheckLock": "",
        "ScanningAcceleration": "",
        "ScanningDecelerationRange": "",
        "ConstSpeedRange": "",
        "LdMaxSpeed": "",
        "LdMinSpeed": "",
        "LdProcessBeload": "",
        "ConstSpeedTime": "",
        "LdSamplingTime": "",
        "LdEndScanningSpeed": "",
        "IsAdvanceApplyParking": "",
        "LdLegalEmissionLimit": "",
        "LdRatedPowerLowSh": "",
        "LdRatedPowerHighSh": "",
        "LdRatedSpeedSh": "",
        "HsuLimit": "",
        "RpmLimit": "",
        "Station": "",
        "WhetherToReturnWeb": "",
        "VehId": "",
        "IdleCheckTime": "",
        "HIdleCheckTime": "",
        "FatCheckTimes": "",
        "LdAmendmentMode": "",
        "LdAmendmentDryair": "",
        "LdAmendmentCoefficient": "",
        "TmSetMileageMax": "",
        "LdFuelDensity": "",
        "LdFuelOilViscosity": "",
        "LdTemperature": "",
        "EngineModel": "",
        "EngineType": "",
        "WheelSpan": "",
        "EngineCap": "",
        "LpgTankNo": "",
        "LpgTankModel": "",
        "ValidationDate": "",
        "TaximeterMake": "",
        "TaximeterModel": "",
        "UpperDeck": "",
        "LowerDeck": "",
        "Standing": "",
        "CSA": "",
        "CSA1": "",
        "CSA2": "",
        "CSA3": "",
        "CSA4": "",
        "CSA5": "",
        "CSA6": "",
        "CSA7": "",
        "VhclModelNum": "",
        "VhclPrmyColorCode": "",
        "VhclScndColorCode": "",
        "CountryPlaceOfOrigin": "",
        "CylinderCapacity": "",
        "AllClasserExceptBus": "",
        "PrivioursClass": "",
        "ExRegistrationMark": "",
        "OriginalRegistration": "",
        "VhclPgvWght": "",
        "PermittedGrossCombinedWeight": "",
        "PrvtRoadVhclInd": "",
        "VhclLugWght": "",
        "StatisticInfoCode": "",
        "TricycleSingleShaft": "",
        "TyreSizeAxle1": "",
        "TyreSizeAxle2": "",
        "TyreSizeAxle3": "",
        "TyreSizeAxle4": "",
        "TyreSizeAxle5": "",
        "TyreSizeAxle6": "",
        "TyreSizeAxle7": "",
        "TyreSizeAxle8": "",
        "SldMakeModel": "",
        "EdrdMakeModel": "",
        "SddMakeModel": "",
        "HybdVhclInd": "",
        "KingPinDiameter": "",
        "ElectricMotorNo1": "",
        "ElectricMotorNo2": "",
        "ElectricMotorNo3": "",
        "ElectricMotorNo4": "",
        "ElectricMotorLocation1": "",
        "ElectricMotorLocation2": "",
        "ElectricMotorLocation3": "",
        "ElectricMotorLocation4": "",
        "Gcw": "",
        "BrakeInspItem": "",
        "IsitMomAppt": "",
        "KLimit": "",
        "UnbalAxle1Limit": "",
        "UnbalAxle2Limit": "",
        "UnbalAxle3Limit": "",
        "UnbalAxle4Limit": "",
        "UnbalAxle5Limit": "",
        "UnbalAxle6Limit": "",
        "UnbalAxle7Limit": "",
        "UnbalAxle8Limit": "",
        "BAxle1Limit": "",
        "BAxle2Limit": "",
        "BAxle3Limit": "",
        "BAxle4Limit": "",
        "BAxle5Limit": "",
        "BAxle6Limit": "",
        "BAxle7Limit": "",
        "BAxle8Limit": "",
        "BrakeEfficiencyLimit": "",
        "ParkingEfficiencyLimit": "",
        "AuxiliaryBrakeEfficiencyLimit": "",
        "SetSpeed1": "",
        "SetSpeed2": "",
        "SetSpeed3": "",
        "MinSpeedLimit": "",
        "MaxSpeedLimit": "",
        "SetLimitSpeed": "",
        "SetSddLimitSpeed": "",
        "MinSddSpeedLimit": "",
        "MaxSddSpeedLimit": "",
        "SetMileage1": "",
        "SetMileage2": "",
        "SetMileage3": "",
        "SetMileage4": "",
        "SetMileage5": "",
        "Mileage1Limit": "",
        "Mileage2Limit": "",
        "Mileage3Limit": "",
        "Mileage4Limit": "",
        "Mileage5Limit": "",
        "HighIdleNoLimit": "",
        "HighIdleCOLimit": "",
        "HighIdleHCLimit": "",
        "LambdaMaxLimit": "",
        "LambdaMinLimit": "",
        "IdleNoLimit": "",
        "IdleCOLimit": "",
        "IdleHCLimit": "",
        "SootMassLimit": "",
        "IntensityMinLimit": "100",
        "IntensityMaxLimit": "100000",
        "AuxIntensityMinLimit": "100",
        "AuxIntensityMaxLimit": "100000",
        "MainVOffsetMinLimit": "-999",
        "MainVOffsetMaxLimit": "999",
        "DippedVOffsetMinLimit": "-999",
        "DippedVOffsetMaxLimit": "175",
        "AuxMainVOffsetMinLimit": "",
        "AuxMainVOffsetMaxLimit": "",
        "LeftAuxHOffsetMinLimit": "",
        "LeftAuxHOffsetMaxLimit": "",
        "RightAuxHOffsetMinLimit": "",
        "RightAuxHOffsetMaxLimit": "",
        "LeftDippedHOffsetMinLimit": "",
        "LeftDippedHOffsetMaxLimit": "",
        "RightDippedHOffsetMinLimit": "-175",
        "RightDippedHOffsetMaxLimit": "999",
        "LeftMainHOffsetMinLimit": "",
        "LeftMainHOffsetMaxLimit": "",
        "RightMainHOffsetMinLimit": "-999",
        "RightMainHOffsetMaxLimit": "999",
        "DippedIntensityMaxLimit": "100000",
        "DippedIntensityMinLimit": "100",
        "HpLimit": "",
        "RpmHighLimit": "",
        "RpmLowLimit": ""

      },
      "Users": {
        "Admin": "Admin"
      },
      "IsVeesEnabled": "false",
      "AllowedHosts": "*",
      "KnownProxies": "172.31.39.157",
      "Vehicle_Service_Url": "http://18.162.190.139:30032",
      "Centre_Service_Url": "http://18.162.190.139:30034",
      "Inspection_Service_Url": "http://18.162.190.139:30033",
      "Appointment_Service_Url": "http://18.162.190.139:30031",
      "Lane_Service_Url": "http://18.162.190.139:30037",
      "Artu_Service_Url": "http://18.162.190.139:30036"
    }
