apiVersion: v1
kind: Service
metadata:
  name: ui-scs-service-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: ui-scs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021
